### ISSUE TITLE
cannot compile the source code again after doing make clean

### ISSUE THREAD

**Issue by foss-pravin** [paralus/paralus#31]

**Comment by meain** [comment]
`make clean` deletes all the generated proto files as of now. We are changing that behavior in https://github.com/paralus/paralus/pull/32 as it can be confusing. But as of now, what I would suggest is that you run `make gen-proto && make build-proto && make build` and that should give you a paralus binary. You should also be able to just run `go run main.go` as the last step instead of `make build`.

If you are running into any other issues, drop in a log of the failure so that we will have more context around what exactly might be going wrong.

**Comment by pravin-rafay** [comment]
pravin@Pravins-MacBook-Pro paralus % make build-proto
rm -rf ./gen
find . -name "*.pb*" -type f -delete
buf build
buf generate
Failure: plugin openapiv2: could not find protoc plugin for name openapiv2
make: *** [build-proto] Error 1

**Comment by meain** [comment]
@pravin-rafay You will have to install some requirements. You can run the following commands to fetch those.

```
go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
```

> Make sure your `$GOPATH/bin` is in `$PATH`.

---

We have reworked the make script in https://github.com/paralus/paralus/pull/32 to make it so that `make clean` does not delete the generated proto files but just the binary artifact.

**Comment by niravparikh05** [comment]
@foss-pravin let us know if you were able to solve this issue by following above instructions and compile/build Paralus successfully.

**Comment by meain** [comment]
@foss-pravin I hope this issues is now solved. I am closing the issue, but feel free to reopen if you are still running into any problems. :D
